create table log4j
(
	Id int not null auto_increment
		primary key,
	level varchar(255) default '' not null,
	category varchar(255) default '' not null,
	thread varchar(255) default '' not null,
	time varchar(30) default '' not null,
	location varchar(255) default '' not null,
	note text null
)
;

comment on column log4j.level is '优先级'
;

comment on column log4j.category is '类目'
;

comment on column log4j.thread is '进程'
;

comment on column log4j.time is '时间'
;

comment on column log4j.location is '位置'
;

comment on column log4j.note is '日志信息'
;











INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:07:50:881', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:07:51:083', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:08:21:588', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:08:21:789', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:09:12:869', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:09:13:421', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(6)-127.0.0.1', '2019-06-14 20:09:14:949', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-1', '2019-06-14 20:09:36:012', 'com.strongman.jinwei.controller.UserController.list(UserController.java:67)', 'Warn Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-1', '2019-06-14 20:09:36:015', 'com.strongman.jinwei.controller.UserController.list(UserController.java:68)', 'Error Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:10:50:656', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:10:51:227', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(4)-127.0.0.1', '2019-06-14 20:10:52:786', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-1', '2019-06-14 20:11:21:914', 'com.strongman.jinwei.controller.UserController.list(UserController.java:67)', 'Warn Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-1', '2019-06-14 20:11:21:916', 'com.strongman.jinwei.controller.UserController.list(UserController.java:68)', 'Error Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-3', '2019-06-14 20:11:23:569', 'com.strongman.jinwei.controller.UserController.list(UserController.java:67)', 'Warn Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-3', '2019-06-14 20:11:23:571', 'com.strongman.jinwei.controller.UserController.list(UserController.java:68)', 'Error Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:13:20:004', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:13:20:176', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:24:00:818', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:24:00:975', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:24:17:573', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:24:18:062', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(10)-127.0.0.1', '2019-06-14 20:24:19:655', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-1', '2019-06-14 20:25:38:388', 'com.strongman.jinwei.controller.UserController.list(UserController.java:67)', 'Warn Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-1', '2019-06-14 20:25:38:390', 'com.strongman.jinwei.controller.UserController.list(UserController.java:68)', 'Error Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-3', '2019-06-14 20:25:38:828', 'com.strongman.jinwei.controller.UserController.list(UserController.java:67)', 'Warn Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-3', '2019-06-14 20:25:38:830', 'com.strongman.jinwei.controller.UserController.list(UserController.java:68)', 'Error Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-5', '2019-06-14 20:25:39:290', 'com.strongman.jinwei.controller.UserController.list(UserController.java:67)', 'Warn Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'com.strongman.jinwei.controller.UserController', 'http-nio-8899-exec-5', '2019-06-14 20:25:39:292', 'com.strongman.jinwei.controller.UserController.list(UserController.java:68)', 'Error Message!');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-14 20:33:59:828', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-14 20:34:00:032', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-17 19:45:46:603', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-17 19:45:47:965', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'org.springframework.scheduling.quartz.LocalDataSourceJobStore', 'QuartzScheduler_schedulerFactoryBean-MS-20181108LCXP1560771944192_MisfireHandler', '2019-06-17 19:45:50:388', 'org.quartz.impl.jdbcjobstore.JobStoreSupport$MisfireHandler.manage(JobStoreSupport.java:3956)', 'MisfireHandler: Error handling misfires: Database error recovering from misfires.');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'org.quartz.core.ErrorLogger', 'schedulerFactoryBean_QuartzSchedulerThread', '2019-06-17 19:45:50:390', 'org.quartz.core.ErrorLogger.schedulerError(QuartzScheduler.java:2425)', 'An error occurred while scanning for the next triggers to fire.');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(6)-127.0.0.1', '2019-06-17 19:45:52:061', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-17 19:47:50:047', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-17 19:47:50:764', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(7)-127.0.0.1', '2019-06-17 19:47:52:822', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-17 19:49:55:744', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-17 19:49:56:475', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.mongo.MongoHealthIndicator', 'RMI TCP Connection(6)-127.0.0.1', '2019-06-17 19:50:27:093', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'MongoDB health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(6)-127.0.0.1', '2019-06-17 19:50:28:116', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-17 19:51:46:739', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-17 19:51:47:454', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.mongo.MongoHealthIndicator', 'RMI TCP Connection(6)-127.0.0.1', '2019-06-17 19:52:18:156', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'MongoDB health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(6)-127.0.0.1', '2019-06-17 19:52:19:180', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-17 19:54:30:115', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-17 19:54:30:876', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.mongo.MongoHealthIndicator', 'RMI TCP Connection(4)-127.0.0.1', '2019-06-17 19:55:01:646', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'MongoDB health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.redis.RedisHealthIndicator', 'RMI TCP Connection(4)-127.0.0.1', '2019-06-17 19:55:02:677', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'Redis health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-17 19:55:54:839', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-17 19:55:55:593', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.actuate.mongo.MongoHealthIndicator', 'RMI TCP Connection(12)-127.0.0.1', '2019-06-17 19:56:26:175', 'org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:89)', 'MongoDB health check failed');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 14:35:23:322', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 14:35:23:876', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 14:38:04:632', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 14:38:04:927', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('ERROR', 'org.quartz.simpl.SimpleThreadPool', 'WorkerThread-LastJob', '2019-06-18 14:39:17:169', 'org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:585)', 'Error while executing the Runnable: ');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 14:39:19:275', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 14:39:19:473', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 15:01:15:911', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 15:01:16:437', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 15:07:46:847', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 15:07:47:369', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 19:29:21:879', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 19:29:22:393', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 19:30:36:866', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 19:30:37:352', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 19:33:01:507', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 19:33:01:721', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 19:36:26:860', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 19:36:27:061', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 19:39:49:627', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 19:39:49:821', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 19:42:17:500', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 19:42:18:133', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-18 19:47:24:237', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-18 19:47:24:455', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'com.alibaba.druid.pool.DruidDataSource', 'main', '2019-06-20 09:17:33:341', 'com.alibaba.druid.pool.DruidDataSource.getConnectionDirect(DruidDataSource.java:1017)', 'not full timeout retry : 1');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-20 09:17:42:734', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-20 09:17:43:289', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver', 'http-nio-8899-exec-1', '2019-06-20 09:17:56:833', 'org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.logException(AbstractHandlerExceptionResolver.java:198)', 'Resolved [com.strongman.jinwei.utils.exception.BusinessException]');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver', 'http-nio-8899-exec-3', '2019-06-20 09:18:22:527', 'org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.logException(AbstractHandlerExceptionResolver.java:198)', 'Resolved [com.strongman.jinwei.utils.exception.BusinessException]');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver', 'http-nio-8899-exec-6', '2019-06-20 09:18:52:940', 'org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver.logException(AbstractHandlerExceptionResolver.java:198)', 'Resolved [com.strongman.jinwei.utils.exception.BusinessException]');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-20 09:18:55:677', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-20 09:18:55:939', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-20 09:20:17:777', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-20 09:20:18:330', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-20 09:21:29:005', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-20 09:21:29:243', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'restartedMain', '2019-06-27 14:48:57:880', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'restartedMain', '2019-06-27 14:48:58:482', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 17:30:01:380', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 17:30:02:719', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 17:33:19:024', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 17:33:20:261', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 19:44:09:810', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 19:44:11:019', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 19:46:39:940', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 19:46:41:448', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 19:49:05:481', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 19:49:06:720', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 19:51:54:415', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 19:51:55:703', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.jms.listener.DefaultMessageListenerContainer', 'DefaultMessageListenerContainer-1', '2019-06-27 19:51:56:476', 'org.springframework.jms.listener.AbstractMessageListenerContainer.invokeErrorHandler(AbstractMessageListenerContainer.java:929)', 'Execution of JMS message listener failed, and no ErrorHandler has been set.');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 20:01:54:732', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 20:01:55:992', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.jms.listener.DefaultMessageListenerContainer', 'DefaultMessageListenerContainer-1', '2019-06-27 20:01:56:539', 'org.springframework.jms.listener.AbstractMessageListenerContainer.invokeErrorHandler(AbstractMessageListenerContainer.java:929)', 'Execution of JMS message listener failed, and no ErrorHandler has been set.');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 20:03:00:001', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 20:03:01:250', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.jms.listener.DefaultMessageListenerContainer', 'DefaultMessageListenerContainer-1', '2019-06-27 20:03:01:814', 'org.springframework.jms.listener.AbstractMessageListenerContainer.invokeErrorHandler(AbstractMessageListenerContainer.java:929)', 'Execution of JMS message listener failed, and no ErrorHandler has been set.');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 20:05:35:502', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 20:05:36:769', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-27 20:08:58:589', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-27 20:08:59:833', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-28 11:31:47:430', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-28 11:31:48:669', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration', 'main', '2019-06-28 11:34:16:273', 'org.springframework.boot.autoconfigure.orm.jpa.JpaBaseConfiguration$JpaWebConfiguration$JpaWebMvcConfiguration.openEntityManagerInViewInterceptor(JpaBaseConfiguration.java:237)', 'spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning');
INSERT INTO jinweidb.log4j (level, category, thread, time, location, note) VALUES ('WARN', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration', 'main', '2019-06-28 11:34:17:470', 'org.springframework.boot.autoconfigure.freemarker.FreeMarkerAutoConfiguration.checkTemplateLocationExists(FreeMarkerAutoConfiguration.java:70)', 'Cannot find template location(s): [classpath:/templates/] (please add some templates, check your FreeMarker configuration, or set spring.freemarker.checkTemplateLocation=false)');




















